### ISSUE TITLE
Implementar model e service de usuário 

### ISSUE THREAD

**Issue by sarahraquel** [bti-imd/IntegraTI-Web#14]
Seguindo documentação da api, usuário deverá conter os seguintes campos:
	id_user int,
	name varchar(100) not null,
	sigaa_matricula varchar(15) not null,
	sigaa_user_name varchar(30) not null,
	sigaa_password varchar(100) not null,
	path_foto varchar(255) not null,

**Comment by weslenbreno** [comment]
Criei um que não estava seguindo essa documentação, vou alterar e depois fecho essa Issue.
